### ISSUE TITLE
undark.c:922:Cannot allocate 4194 bytes for mapped data

### ISSUE THREAD

**Issue by moses3009** [witwall/undark#2]
Hi, 
I run the app on win7 and I get the above error. Any hint for this?

**Comment by witwall** [comment]
got the same error on any sqlite db?

@inflex would you like to response this issue?

**Comment by inflex** [comment]
On 17/03/16 22:32, Steven Lee wrote:

> got the same error on any sqlite db?

Seems rather odd that the system fails to allocate ~4K of memory for 
this.  Perhaps some debug-info before the malloc request to see what 
payload->length really is?  I probably should also one day move from 
"char" to uint8_t for blobs of binary.

```
         payload->mapped_data = malloc( (payload->length +100) 
```

*sizeof(char) );
             if ( !payload->mapped_data ) {
                 fprintf(stderr,"%s:%d:ERROR: Cannot allocate %ld bytes 
for mapped data\n", FL, (long int)payload->length +100);
                 return -1;
             }

**Comment by moses3009** [comment]
@witwall - I did try it on 2 DBs - one is from watsapp and second from android phone; apps is crashing on both; on whatsapp db, sometime crash before getting the error message , and extract about 25% of the file; when error is printed out and crash, it take about 50%. This percentage is from currently records, not including deleted ones, which I not know how many are

**Comment by witwall** [comment]
could you give me a sample db? so I can test it.

**Comment by witwall** [comment]
please open issue here, https://github.com/inflex/undark/issues
