### ISSUE TITLE
Character encoding problem

### ISSUE THREAD

**Issue by Zergius2** [witwall/undark#5]
Hi

Great stuff!    But what I've found out,  that it works wrong with non-english characters in database.  It makes dots out of any for example cyryllic letters:
79,NULL,"+380966478305","...... ..........","...... ..........",384,384,"........","
Is there any possibility to fix this?  Or to point to Undark which encoding to use?  Thanks.

**Comment by witwall** [comment]
please open issue here,
https://github.com/inflex/undark/issues
